name: Deploy to main

on:
  pull_request:
    branches:
      - main
    types:
      - merged

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        run: |
          npm run docs:build
          git config --global user.name "JaxxMoss"
          git config --global user.email "j.d.malotaux@gmail.com"
          git rm -rf .
          cp -r .vitepress/dist/* .
          git add .
          git commit -m "Deploy to main"
          git push origin main