name: Release Build

on:
  push:
    branches:
      - "release/**"

permissions:
  contents: write

jobs:
  docs-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the release branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from branch name
        id: extract
        shell: bash
        run: |
          version="${GITHUB_REF##*/}"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Set up Git
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Install dependencies and build docs
        shell: bash
        run: |
          npm ci
          npm run docs:build

      - name: Move built docs to root
        shell: bash
        run: |
          mv .vitepress/dist/* .
          rm -rf .vitepress

      - name: Commit and push build output
        shell: bash
        run: |
          git add -A
          git commit -m "Macrame documentation release: ${{ steps.extract.outputs.version }}"
          git push origin ${{ github.ref }}

      - name: Merge release branch into main
        shell: bash
        run: |
          git fetch origin main
          git checkout main
          git merge --allow-unrelated-histories -X theirs ${{ github.ref }} -m "Merging release version ${{ steps.extract.outputs.version }} into main"
          git push origin main
